version: '3.8'

x-basicenvs: &basicenvs
  TZ: Europe/Berlin
  JWT_SECRET: supersecret

x-basicopts: &basicopts
  tty: true
  restart: always
  #env_file: .env  

services:
  webclient:
    <<: *basicopts
    container_name: webclient
    image: project_b/webclient:latest
    #TODO: conect server to docker file and compose
    # depends_on:
    #   backend: 
    #     condition: service_healthy
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    command: npx expo start
    environment:
      - NODE_ENV=development